all:
	g++ -o LocalizationEntryTest LocalizationEntryTest.cpp LocalizationEntry.cpp
	g++ -o LocalizationStringTest LocalizationStringTest.cpp LocalizationString.cpp LocalizationEntry.cpp
debug:
	g++ -o LocalizationEntryTest LocalizationEntryTest.cpp LocalizationEntry.cpp -g
	g++ -o LocalizationStringTest LocalizationStringTest.cpp LocalizationString.cpp LocalizationEntry.cpp
clean:
	rm -rf LocalizationEntryTest LocalizationStringTest
